archives:
  - id: archive
    name_template: '{{ .Binary }}-{{ .Tag }}-{{ .Os }}-{{ .Arch }}'
before:
  hooks:
    - make build_provider
builds:
  - binary: pulumi-resource-kubernetes-ingress-nginx
    dir: provider
    env:
      - CGO_ENABLED=0
    goarch:
      - amd64
      - arm64
    goos:
      - darwin
      - windows
      - linux
    ldflags:
      - -X github.com/cuemby/pulumi-xyz/pkg/version.Version={{.Tag }}
    main: ./cmd/pulumi-resource-xyz/
changelog:
  skip: true
release:
  disable: true
snapshot:
  name_template: '{{ .Tag }}-SNAPSHOT'