# coding=utf-8
# *** WARNING: this file was generated by Pulumi SDK Generator. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

from . import _utilities
import typing
# Export this package's modules as members:
from .kubernetes_xyz import *
from .provider import *
from ._inputs import *
from . import outputs
_utilities.register(
    resource_modules="""
[
 {
  "pkg": "kubernetes-xyz",
  "mod": "index",
  "fqn": "pulumi_kubernetes_xyz",
  "classes": {
   "kubernetes-xyz:index:KubernetesXyz": "KubernetesXyz"
  }
 }
]
""",
    resource_packages="""
[
 {
  "pkg": "kubernetes-xyz",
  "token": "pulumi:providers:kubernetes-xyz",
  "fqn": "pulumi_kubernetes_xyz",
  "class": "Provider"
 }
]
"""
)
