// *** WARNING: this file was generated by Pulumi SDK Generator. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Cuemby.KubernetesXyz.Inputs
{

    public sealed class KubernetesXyzGlobalArgs : global::Pulumi.ResourceArgs
    {
        public KubernetesXyzGlobalArgs()
        {
        }
        public static new KubernetesXyzGlobalArgs Empty => new KubernetesXyzGlobalArgs();
    }
}
